image: registry.gitlab.com/pages/hugo/hugo_extended:0.115.0

variables:
  HUGO_ENV: production
  THEME_URL: "github.com/vimux/mainroad"

default:
  before_script:
    - apk add --no-cache go curl bash nodejs
    - hugo mod get -u $THEME_URL
test:
  cache:
    key:
      prefix: hugo-gen
      files:
        - config.yaml
    paths:
      - resources
    unprotect: true
  script:
    - hugo --minify --cacheDir $CI_PROJECT_DIR/resources
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

pages:
  cache:
    key:
      prefix: hugo-gen
      files:
        - config.yaml
    paths:
      - resources
    unprotect: true
  script:
    - hugo --minify --cacheDir $CI_PROJECT_DIR/resources
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
